// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXHgZh9dxWsbiR2uJ1G5dsKfnsDL0qzEY',
    appId: '1:44793118649:web:99dbad2602d472b6654068',
    messagingSenderId: '44793118649',
    projectId: 'screenview-demo',
    authDomain: 'screenview-demo.firebaseapp.com',
    storageBucket: 'screenview-demo.appspot.com',
    measurementId: 'G-Z83Z6SKSPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5zkyZdgxJyrAwCu82hd3_qZpAxPaGfsg',
    appId: '1:44793118649:android:ac2b4c544bb4e5d1654068',
    messagingSenderId: '44793118649',
    projectId: 'screenview-demo',
    storageBucket: 'screenview-demo.appspot.com',
  );
}
